services:
  postgres:
    container_name: task_application_progress
    image: postgres
    environment:
      - POSTGRES_USER=task_admin
      - POSTGRES_PASSWORD=task_application@045
      - POSTGRES_DB=task_database
    ports:
      - 5432:5432
    volumes:
      - task_volume_postgress:/var/lib/postgresql/data/


volumes:
  task_volume_postgress: